allow-branch               = [ "main", "!HEAD" ]
consolidate-commits        = true
dependent-version          = "upgrade"
enable-all-features        = true
enable-features            = [  ]
metadata                   = "optional"
owners                     = [ "team@t3rn.io" ]
pre-release-commit-message = "build(cargo-release): Release version {{version}}"
pre-release-replacements   = [  ]
publish                    = true
push                       = false
push-options               = [  ]
push-remote                = "origin"
release                    = true
shared-version             = true
sign-commit                = false # TODO
sign-tag                   = false # TODO
tag                        = true
tag-message                = "build(cargo-release): Release version {{version}}"
tag-name                   = "v{{version}}"
tag-prefix                 = ""
verify                     = false # TODO there is some weird compiler bug when publishing the crates, errors exist which don't when building/checking so for now we dont verify
