name: Release XBI

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "main"
jobs:
  publish:
    if: ${{ !contains(github.event.head_commit.message, 'build(cargo-release):') }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate semantic version
        id: version
        uses: paulhatch/semantic-version@v5.0.0-alpha
        with:
          tag_prefix: "v"
          major_pattern: "feat!:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "json"

      - name: Install cargo release
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-release
          # version: "0.21.4" Last known release to have --token flag, but doesnt recover already published crates

      - name: Login to cargo registry
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # TODO there is some weird compiler bug when publishing the crates, errors exist which don't when building/checking so for now we dont verify
      # TODO reenable substrate abi in the next PR
      - name: Release
        id: release
        run: cargo release --execute --no-confirm --no-verify --exclude substrate-abi --exclude xbi-client --tag-prefix "" ${{ steps.version.outputs.version }}

      - name: Send telegram message on primitives release failure
        if: failure() && steps.release.outcome == 'failure'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            `XBI` *failed to publish*! 👻

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
